-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#141318",
  base01 = "#0e0e13",
  base02 = "#1c1b20",
  base03 = "#48464f",
  base04 = "#c9c5d0",
  base05 = "#e5e1e9",
  base06 = "#313036",
  base07 = "#3a383e",

  base08 = "#e7a4c0",
  base09 = "#ecb8ce",
  base0A = "#c8c3dc",
  base0B = "#c7bfff",
  base0C = "#613b4d",
  base0D = "#463f77",
  base0E = "#474459",
  base0F = "#aaa3c9",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#463f77',
  fg = '#e5deff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#dc7ca4',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#928f99',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ecb8ce',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c8c3dc',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#5e5791',
})
